export const usersData = [
  { email: "d", password: "d", profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png", },
  {
    firstName: "Danail",
    lastName: "Todorov",
    fullName: "Danail Todorov",
    email: "danail@fdm.com",
    password: "1234",
    personalEmail: "danail@gmail.com",
    phoneNumber: "+44888888888",
    profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png",
    position: "",
    location: "",
    dateOfBirth: "",
    roles: [""],
    skills: [""],
    toImprove: [""],
    interests: [""],
    registrationDate: "",
  },

  { email: "j", password: "j", profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png", },
  {
    firstName: "Jay",
    lastName: "Patel",
    fullName: "Jay Patel",
    email: "jay@fdm.com",
    password: "1234",
    personalEmail: "jay@gmail.com",
    phoneNumber: "+44888888888",
    position: "",
    location: "",
    dateOfBirth: "",
    roles: [""],
    skills: ["Java","Python","Web Development","Retail/Sales"],
    toImprove: [""],
    interests: [""],
    registrationDate: "",
    profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png",
  },

  { email: "c", password: "c", profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png", },
  {
    firstName: "Cristian",
    lastName: "Mina",
    fullName: "Cristian Mina",
    email: "cristian@fdm.com",
    password: "1234",
    personalEmail: "cristian@gmail.com",
    phoneNumber: "+44888888888",
    position: "",
    location: "",
    dateOfBirth: "",
    roles: [""],
    skills: [""],
    toImprove: [""],
    interests: [""],
    registrationDate: "",
    profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png",
  },
  {
    firstName: "Dennis",
    lastName: "Grigoryev",
    fullName: "Dennis Grigoryev",
    email: "dennis@fdm.com",
    password: "1234",
    personalEmail: "dennis@gmail.com",
    phoneNumber: "+44888888888",
    position: "",
    location: "",
    dateOfBirth: "",
    roles: [""],
    skills: [""],
    toImprove: [""],
    interests: [""],
    registrationDate: "",
    profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png",
  },

  { email: "m", password: "m", profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png", },
  {
    firstName: "Miles",
    lastName: "Richards",
    fullName: "Miles Richards",
    email: "miles@fdm.com",
    password: "1234",
    personalEmail: "miles@gmail.com",
    phoneNumber: "+44888888888",
    position: "",
    location: "",
    dateOfBirth: "",
    roles: [""],
    skills: [""],
    toImprove: [""],
    interests: [""],
    registrationDate: "",
    profilePicture: "https://bootdey.com/img/Content/avatar/avatar7.png",
  },
]

export const categoriesData = [
  { value: "teamwork", label: "Teamwork" },
  {
    value: "conflictResolution",
    label: "Conflict resolution",
    isSubcategory: true,
  },
  { value: "communication", label: "Communication" },
  { value: "customerService", label: "Customer service", isSubcategory: true },
  { value: "problemSolving", label: "Problem solving" },
  {
    value: "criticalThinking",
    label: "Critical thinking",
    isSubcategory: true,
  },
  { value: "proactiveness", label: "Proactiveness", isSubcategory: true },
  { value: "timeManagement", label: "Time management" },
  { value: "interpersonalSkills", label: "Innpm terpersonal skills" },
  { value: "settingGoals", label: "Setting goals", isSubcategory: true },
  {
    value: "acceptingFeedback",
    label: "Accepting feedback",
    isSubcategory: true,
  },
  { value: "flexibility", label: "Flexibility", isSubcategory: true },
  { value: "leadership", label: "Leadership", isSubcategory: true },
  { value: "listening", label: "Listening", isSubcategory: true },
  { value: "patience", label: "Patience", isSubcategory: true },
  { value: "writing", label: "Writing" },
  { value: "organisation", label: "Organisation" },
]
